### ISSUE TITLE
[v11] Message Input Buttons get messed up when the plugin is on

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#173]
**Describe the bug**
Look at the screenshots:
* The plugin suddenly creates a square (instead of a separator near "Send Message" button from Accessibility discord settings).
* The plugin doesn't behave well with remove chat buttons custom css: it creates an empty space instead. 

I have all features about message input buttons off in the plugin settings.

**Screenshots**

1. with Custom CSS to hide Sticker button 
![Image](https://github.com/user-attachments/assets/e2fefea7-769b-4688-bd5a-be8d24053038)
2. without that Custom CSS :
![Image](https://github.com/user-attachments/assets/4177618a-4868-4a1d-ae33-ba2bc9a73036)
3. with only custom css on (plugin off):
![Image](https://github.com/user-attachments/assets/6bcdd376-5051-4ffd-bb79-5c72df54b275)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Discord Version: Stable
 - Enabled Theme(s): None
 - Custom CSS in question is taken from the BetterDiscord server: 

```css
@import url("https://smolalli.github.io/Themes/Snippets/removechatbuttons.css");
:root {
    /* Chat Area */
    --gift: none;
    /*--gif: none;*/
    --sticker: none;
    /*--emoji: none;*/
    /*--upload: none;*/
    --activity: none;
    /* Channels Sidebar */
    --invite: none;
    /*--guide: none;  Server Guide */
    /*--channels: none;  Channels & Roles */
    /*--browse: none;  Browse Channels */
    /*--members: none;*/
    --server-shop: none;
    --events: none;
    --boost: none;
    /* Boost Bar */
    /* DM Area */
    --friends: none;
    --store: none;
    /* Nitro store */
    --shop: none;
    /* Discover Button */
    --discover: none;
    --discover-indicator: 0;
    /* Make sure to add this if you are using the previous line */
}
```
